# Generated by Django 3.1 on 2021-03-04 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panel', '0004_full_sheet_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='VSG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=250, null=True)),
                ('area_slug', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='vsg')),
                ('is_default', models.BooleanField(blank=True, default=False, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VSG_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='panel.product')),
                ('fk_vsg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vsg.vsg')),
            ],
        ),
    ]
