# Generated by Django 3.1 on 2021-03-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vsg', '0002_auto_20210305_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsg_product',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
