# Generated by Django 3.1 on 2021-04-29 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_page_handler'),
        ('vsg', '0003_vsg_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vsg_product',
            name='fk_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.product'),
        ),
        migrations.AlterField(
            model_name='vsg_product',
            name='fk_vsg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vsg.vsg'),
        ),
    ]
