# Generated by Django 3.1 on 2021-03-02 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name_slug', models.CharField(blank=True, max_length=100, null=True)),
                ('intro', models.TextField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='product')),
            ],
        ),
        migrations.CreateModel(
            name='Full_Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='portfolio/full-sheet')),
                ('fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.product')),
            ],
        ),
    ]
