# Generated by Django 3.1 on 2021-03-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_full_sheet_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('name_slug', models.CharField(blank=True, max_length=250, null=True)),
                ('title', models.CharField(blank=True, max_length=350, null=True)),
                ('intro', models.CharField(blank=True, max_length=350, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
