# Generated by Django 3.1 on 2021-03-16 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, default=0, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='events')),
                ('fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.events')),
            ],
        ),
    ]
