# Generated by Django 3.1 on 2021-03-16 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_event_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
