# Generated by Django 3.1.1 on 2021-12-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_page_handler'),
    ]

    operations = [
        migrations.AddField(
            model_name='full_sheet',
            name='finish',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='full_sheet',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='full_sheet',
            name='size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
