# Generated by Django 3.1.1 on 2021-12-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_auto_20211225_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='full_sheet',
            name='has_detail',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
