# Generated by Django 3.1.1 on 2022-01-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_full_sheet_has_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='full_sheet',
            name='index',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
