# Generated by Django 3.1.1 on 2022-01-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_auto_20220108_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='full_sheet',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
