# Generated by Django 3.1.1 on 2022-01-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_auto_20220108_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='full_sheet',
            name='number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
